Agentforce/force-app/main/default/objects/Account/fields/Legacy_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Id used on the Legacy System</description>
    <externalId>true</externalId>
    <label>Legacy Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Agentforce/force-app/main/default/objects/OCS_Config_Settings_CSH__c/OCS_Config_Settings_CSH__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting used to control and enabling and disabling of automation in the system.</description>
    <label>OCS Config Settings CSH</label>
</CustomObject>

Agentforce/force-app/main/default/objects/OCS_Config_Settings_CSH__c/fields/Flows_Disabled__c.field-meta.xml
<CustomField>
    <fullName>Flows_Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to control whether or not flows will run within a transaction</description>
    <inlineHelpText>Check this to disable all flows in the system</inlineHelpText>
    <label>Flows Disabled</label>
    <type>Checkbox</type>
</CustomField>

Agentforce/force-app/main/default/objects/OCS_Config_Settings_CSH__c/fields/Migration_Flows_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Migration_Flows_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Migration Flows Enabled</label>
    <type>Checkbox</type>
</CustomField>

Agentforce/force-app/main/default/objects/OCS_Config_Settings_CSH__c/fields/Triggers_Disabled__c.field-meta.xml
<CustomField>
    <fullName>Triggers_Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to control whether or not triggers will be executed</description>
    <inlineHelpText>Check this box to disable triggers across the system</inlineHelpText>
    <label>Triggers Disabled</label>
    <type>Checkbox</type>
</CustomField>

Agentforce/force-app/main/default/objects/OCS_Config_Settings_CSH__c/fields/Validation_Rules_Disabled__c.field-meta.xml
<CustomField>
    <fullName>Validation_Rules_Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to control whether validation rules will run in a transaction</description>
    <inlineHelpText>Check this box to disable all validation rules in the system</inlineHelpText>
    <label>Validation Rules Disabled</label>
    <type>Checkbox</type>
</CustomField>

Agentforce/force-app/main/default/classes/OCS_PostMigrationScriptBatchTest.cls
/************************************************************************************************
* @company          Globant
* @author           Anay Karkhanis href=<anay.karkhanis@globant.com>
* @project          OCS
* @name             OCS_PostMigrationScriptBatchTest
* @description      Test class OCS_PostMigrationScriptBatch batch process 
* @dependencies
* @changes (Version)
* --------   ---   ----------   ---------------------------   -----------------------------------
*            No.   Date         Author                        Description
* --------   ---   ----------   ---------------------------   -----------------------------------
* @version   1.0   2024-01-22   Anay K                        Initial version.
************************************************************************************************/

@isTest
public class OCS_PostMigrationScriptBatchTest {
    
    /**
    * @method       setupTestData
    * @description  setupTestData for Batch Process for object migration 
    * @author       Anay K - 2024-01-22
    */
    @testSetup public static void setupTestData()  {



        OCS_Config_Settings_CSH__c setting = new OCS_Config_Settings_CSH__c();
        setting.Migration_Flows_Enabled__c = false;
        setting.Flows_Disabled__c= true;
        setting.Triggers_Disabled__c= true;
        setting.Validation_Rules_Disabled__c= true;
        insert setting;

        Account objAccount = new Account();
        objAccount.Name ='AccTest';
        objAccount.Legacy_Id__c='Test';
        objAccount.Description = 'Test';
        insert objAccount;

        setting.Migration_Flows_Enabled__c=true;
        update setting;
       
    }    
    
    /**
    * @method       testFieldUpdateForPostMigration
    * @description  Validate the field update which triggers the record flows to execute logic for post migrations
    * @author       Anay K - 2024-01-22
    */
    @isTest static void testFieldUpdateForPostMigration() {  
        Test.startTest();
        Database.executeBatch(new OCS_PostMigrationScriptBatch('Account','Description','Legacy_Id__c != null'), 200);
        Test.stopTest();
        Account objAccount = [Select Id,Description from Account where Name='AccTest' LIMIT 1];
        System.assert(objAccount.Description.endsWith('*'));
    }    
    
    /**
    * @method       testRevertFieldUpdateChangeForPostMigration
    * @description  Validate that the field updated to trigger the record flows in the first batch run
    *               is updated back to it's original value
    * @author       Anay K - 2024-01-22
    */
    @isTest static void testRevertFieldUpdateChangeForPostMigration() {  
        
        Account objAccountToUpdate = [Select Id,Description from Account where Name='AccTest' LIMIT 1];
        objAccountToUpdate.Description +='*' ;
        update objAccountToUpdate;
            
        Test.startTest();
        Database.executeBatch(new OCS_PostMigrationScriptBatch('Account','Description','Legacy_Id__c != null'), 200);
        Test.stopTest();
        Account objAccount = [Select Id,Description from Account where Name='AccTest' LIMIT 1];
        System.assert(!objAccount.Description.endsWith('*'));
        
    }       

}