Agentforce/force-app/main/default/objects/Account/fields/NPS_Surveyor__c.field-meta.xml
<CustomField>
    <fullName>NPS_Surveyor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NPS Surveyor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>User.NPS_Surveyor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>NPS Surveyor</value>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Agentforce/force-app/main/default/objects/NPS__c/NPS__c.object-meta.xml
<CustomObject>
    <description>AD-190 - custom object to capture NPS</description>
    <label>NPS</label>
    <nameField>
        <displayFormat>NPS-{000000}</displayFormat>
        <label>NPS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Agentforce/force-app/main/default/objects/NPS__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>AD-209 - Add Account lookup to NPS object</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NPS</relationshipLabel>
    <relationshipName>NPS</relationshipName>
    <type>Lookup</type>
</CustomField>

Agentforce/force-app/main/default/objects/NPS__c/fields/Average_Score__c.field-meta.xml
<CustomField>
    <fullName>Average_Score__c</fullName>
    <formula>0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Average Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Agentforce/force-app/main/default/objects/NPS__c/fields/NPS_Contact__c.field-meta.xml
<CustomField>
    <fullName>NPS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>AD-181 - Stores the Contact that this NPS record has been generated for</description>
    <label>NPS Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>NPS (NPS Contact)</relationshipLabel>
    <relationshipName>NPS2</relationshipName>
    <type>Lookup</type>
</CustomField>

Agentforce/force-app/main/default/objects/NPS__c/fields/NPS_Surveyor__c.field-meta.xml
<CustomField>
    <fullName>NPS_Surveyor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NPS Surveyor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 2) AND 3</booleanFilter>
        <filterItems>
            <field>User.NPS_Surveyor__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>NPS Surveyor</value>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>NPS3</relationshipName>
    <type>Lookup</type>
</CustomField>

Agentforce/force-app/main/default/objects/NPS__c/fields/Number_of_NPS_Responses__c.field-meta.xml
<CustomField>
    <fullName>Number_of_NPS_Responses__c</fullName>
    <description>AD-180 - Track the total number of responses</description>
    <label>Number of NPS Responses</label>
    <summaryForeignKey>NPS_Response__c.NPS__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Agentforce/force-app/main/default/objects/NPS__c/fields/Recommend_Us_Score__c.field-meta.xml
<CustomField>
    <fullName>Recommend_Us_Score__c</fullName>
    <label>Recommend Us Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Agentforce/force-app/main/default/objects/NPS__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>AD-206 - Add NPS record statuses to track the NPS through it&apos;s lifecycle</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Appointment Required</fullName>
                <default>true</default>
                <label>Appointment Required</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Awaiting Response</fullName>
            </value>
            <value>
                <fullName>Pending Results</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Awaiting Review</fullName>
                <isActive>false</isActive>
                <label>Awaiting Review</label>
            </value>
            <value>
                <fullName>No Response</fullName>
                <isActive>false</isActive>
                <label>No Response</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Agentforce/force-app/main/default/objects/NPS__c/fields/Survey_Category__c.field-meta.xml
<CustomField>
    <fullName>Survey_Category__c</fullName>
    <label>Survey Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Survey_Category</valueSetName>
    </valueSet>
</CustomField>

Agentforce/force-app/main/default/objects/NPS__c/fields/Total_NPS_Score__c.field-meta.xml
<CustomField>
    <fullName>Total_NPS_Score__c</fullName>
    <description>AD-180 - Summary of the score from all related NPS Responses</description>
    <label>Total NPS Score</label>
    <summarizedField>NPS_Response__c.Score__c</summarizedField>
    <summaryForeignKey>NPS_Response__c.NPS__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

Agentforce/force-app/main/default/objects/NPS__c/fields/Visit_Start__c.field-meta.xml
<CustomField>
    <fullName>Visit_Start__c</fullName>
    <description>AD-426 - date and time field to capture the start of the NPS appointment</description>
    <label>Visit Start</label>
    <type>DateTime</type>
</CustomField>

Agentforce/force-app/main/default/objects/NPS__c/fields/Visiting_Comments__c.field-meta.xml
<CustomField>
    <fullName>Visiting_Comments__c</fullName>
    <label>Visiting Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Agentforce/force-app/main/default/objects/NPS__c/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

Agentforce/force-app/main/default/objects/NPS__c/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <description>AD-368 - Add record type for sending NPS Surveys to Contacts</description>
    <label>Contact</label>
</RecordType>

Agentforce/force-app/main/default/objects/NPS_Response__c/NPS_Response__c.object-meta.xml
<CustomObject>
    <description>AD-180 - Represents a question from the NPS and what the response was</description>
    <label>NPS Response</label>
    <nameField>
        <label>NPS Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPS Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Agentforce/force-app/main/default/objects/NPS_Response__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <description>AD-180 - Stores the answer to this question</description>
    <label>Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Agentforce/force-app/main/default/objects/NPS_Response__c/fields/NPS__c.field-meta.xml
<CustomField>
    <fullName>NPS__c</fullName>
    <description>AD-180 - Track the NPS that this response is for</description>
    <label>NPS</label>
    <referenceTo>NPS__c</referenceTo>
    <relationshipLabel>NPS Responses</relationshipLabel>
    <relationshipName>NPS_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Agentforce/force-app/main/default/objects/NPS_Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>AD-376 - Store picklist of NPS Questions</description>
    <label>Question</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contractual Delivery?</fullName>
            </value>
            <value>
                <fullName>How open &amp; honest is our relationship?</fullName>
            </value>
            <value>
                <fullName>How readily available are we to meet you?</fullName>
            </value>
            <value>
                <fullName>Dealing with serious issues?</fullName>
            </value>
            <value>
                <fullName>How innovative and creative are we?</fullName>
            </value>
            <value>
                <fullName>Do our colleagues show good work ethic?</fullName>
            </value>
            <value>
                <fullName>Do we provide accurate information?</fullName>
            </value>
            <value>
                <fullName>Do we look for future opportunities?</fullName>
            </value>
            <value>
                <fullName>Do we support your business needs?</fullName>
            </value>
            <value>
                <fullName>How do we compare to our competitors?</fullName>
            </value>
            <value>
                <fullName>How well do we represent value for money?</fullName>
            </value>
            <value>
                <fullName>How well do you rate our website?</fullName>
            </value>
            <value>
                <fullName>Are we improving?</fullName>
            </value>
            <value>
                <fullName>Further Comments/Easier to work with?</fullName>
            </value>
            <value>
                <fullName>Would you recommend us?</fullName>
            </value>
            <value>
                <fullName>Any questions that we should have asked?</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Agentforce/force-app/main/default/objects/NPS_Response__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>AD-180 - Tracks the score for this NPS response.</description>
    <label>Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Agentforce/force-app/main/default/objects/NPS_Response__c/fields/Suggestion_for_improvement__c.field-meta.xml
<CustomField>
    <fullName>Suggestion_for_improvement__c</fullName>
    <description>AD-180 - Tracks the suggestion for improvement against a Survey Response. Note that this may not be applicable for all questions</description>
    <label>Suggestion For Improvement</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Agentforce/force-app/main/default/objects/NPS_Response__c/fields/Visiting_Comments__c.field-meta.xml
<CustomField>
    <fullName>Visiting_Comments__c</fullName>
    <label>Visiting Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Agentforce/force-app/main/default/objects/User/fields/NPS_Surveyor__c.field-meta.xml
<CustomField>
    <fullName>NPS_Surveyor__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>In addition to their main role does this user also act as an NPS Surveyor?</inlineHelpText>
    <label>NPS Surveyor</label>
    <type>Checkbox</type>
</CustomField>

Agentforce/force-app/main/default/classes/Agentforce/AF_NPSPromptBuilder.cls
/**
 * @Name         AF_NPSPromptBuilder
 * @Author       Agentforce Implementation Team
 * @Date         2025-01-15
 * @Description  Utility class to build structured prompts for Agentforce AI summary generation
 *               from NPS Survey and Response data
 */
public with sharing class AF_NPSPromptBuilder {

    /**
     * Builds a comprehensive prompt string from NPS Survey and its responses
     * @param nps The NPS Survey record with related Account, Contact, Surveyor data
     * @param responses List of NPS Response records for this survey
     * @return Formatted prompt string ready for Agentforce
     */
    public static String buildPromptData(NPS__c nps, List<NPS_Response__c> responses) {
        String prompt = '';

        // Header Section
        prompt += '===== NPS SURVEY DATA =====\n\n';

        // Survey Metadata
        prompt += 'SURVEY INFORMATION:\n';
        prompt += 'Survey Number: ' + nps.Name + '\n';

        if (nps.Account__c != null && nps.Account__r != null) {
            prompt += 'Account: ' + nps.Account__r.Name + '\n';
        }

        if (nps.NPS_Contact__c != null && nps.NPS_Contact__r != null) {
            prompt += 'Contact: ' + nps.NPS_Contact__r.Name + '\n';
        }

        if (nps.NPS_Surveyor__c != null && nps.NPS_Surveyor__r != null) {
            prompt += 'Surveyor: ' + nps.NPS_Surveyor__r.Name + '\n';
        }

        if (nps.Visit_Start__c != null) {
            prompt += 'Survey Date: ' + nps.Visit_Start__c.format('yyyy-MM-dd') + '\n';
        }

        if (nps.Survey_Category__c != null) {
            prompt += 'Category: ' + nps.Survey_Category__c + '\n';
        }

        prompt += '\n';

        // Scores Section
        prompt += 'OVERALL SCORES:\n';

        if (nps.Recommend_Us_Score__c != null) {
            prompt += 'NPS Recommendation Score: ' + nps.Recommend_Us_Score__c + ' / 10\n';
        }

        if (nps.Average_Score__c != null) {
            prompt += 'Average Score: ' + nps.Average_Score__c + '\n';
        }

        if (nps.Total_NPS_Score__c != null) {
            prompt += 'Total Score: ' + nps.Total_NPS_Score__c + '\n';
        }

        if (nps.Number_of_NPS_Responses__c != null) {
            prompt += 'Number of Responses: ' + nps.Number_of_NPS_Responses__c + '\n';
        }

        prompt += '\n';

        // Responses Section
        if (responses != null && !responses.isEmpty()) {
            prompt += 'DETAILED RESPONSES:\n';
            prompt += '---\n';

            for (NPS_Response__c response : responses) {
                if (response.Question__c != null) {
                    prompt += '\nQuestion: ' + response.Question__c + '\n';
                }

                if (response.Score__c != null) {
                    prompt += 'Score: ' + response.Score__c + ' / 10\n';
                }

                if (String.isNotBlank(response.Answer__c)) {
                    prompt += 'Answer: ' + response.Answer__c + '\n';
                }

                if (String.isNotBlank(response.Suggestion_for_improvement__c)) {
                    prompt += 'Suggestions for Improvement: ' + response.Suggestion_for_improvement__c + '\n';
                }

                prompt += '---\n';
            }

            prompt += '\n';
        }

        // Additional Comments
        if (String.isNotBlank(nps.Comments__c)) {
            prompt += 'OVERALL COMMENTS:\n';
            prompt += nps.Comments__c + '\n\n';
        }

        if (String.isNotBlank(nps.Visiting_Comments__c)) {
            prompt += 'VISITING COMMENTS:\n';
            prompt += nps.Visiting_Comments__c + '\n\n';
        }

        // Instructions for AI
        prompt += '===== SUMMARY REQUEST =====\n\n';
        prompt += 'Please analyze the above NPS survey data and provide a comprehensive summary in English that includes:\n\n';
        prompt += '1. EXECUTIVE SUMMARY (2-3 sentences highlighting overall sentiment and key takeaways)\n\n';
        prompt += '2. KEY STRENGTHS (bullet points of positive feedback and high-scoring areas)\n\n';
        prompt += '3. AREAS FOR IMPROVEMENT (bullet points of concerns and low-scoring areas)\n\n';
        prompt += '4. SENTIMENT ANALYSIS (Overall: Positive, Neutral, Negative, or Mixed)\n\n';
        prompt += '5. RECOMMENDED ACTIONS (prioritized list of specific, actionable next steps)\n\n';
        prompt += '6. FOLLOW-UP REQUIRED (Yes/No with brief explanation)\n\n';
        prompt += 'Please format the summary in a professional, concise manner suitable for business stakeholders.\n';

        return prompt;
    }

    /**
     * Validates that NPS record has minimum required data for summary generation
     * @param nps The NPS Survey record
     * @param responses List of NPS Response records
     * @return true if data is sufficient, false otherwise
     */
    public static Boolean hasRequiredData(NPS__c nps, List<NPS_Response__c> responses) {
        if (nps == null) {
            return false;
        }

        // Must have at least one response to generate meaningful summary
        if (responses == null || responses.isEmpty()) {
            return false;
        }

        // Must have Status = Closed
        if (nps.Status__c != 'Closed') {
            return false;
        }

        return true;
    }
}