Agentforce/force-app/main/default/objects/Contract_Line_Item__c/Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <description>AD-736 to create a Contract for &apos;Contractual&apos; Opportunity Product Lines when an Opportunity Stage is &apos;Closed Won&apos; and the Sub-Stage is updated to either &apos;Written Confirmation&apos; or &apos;T&amp;Cs Signed&apos;</description>
    <label>Contract Line Item</label>
    <nameField>
        <displayFormat>CLI-{0000000}</displayFormat>
        <label>CLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Agentforce/force-app/main/default/objects/Contract_Line_Item__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <description>AD-171 - Add Product Family to Contract Line Item</description>
    <formula>TEXT(Product__r.Family)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

Agentforce/force-app/main/default/classes/Other/ContractUtilities.cls
/*******************************************************************************************
* @Name         ContractUtilities
* @Author       Jake Lankester <jake.lankester@globant.com>
* @Date         28/09/2023
* @Description  Class to store utility methods for the Contract Object
*******************************************************************************************/
/* MODIFICATION LOG*
* Version          Author       Date               Description
*-------------------------------------------------------------------------------------------
*  1.0             Jake L      	28/09/2023         Initial Creation                                                      
*******************************************************************************************/
public with sharing class ContractUtilities {
   
  public static String processServiceSummary(List<Contract_Line_Item__c> contractLineItems){
        Set<String> productFamilies = new Set<String>();

        for(Contract_Line_Item__c lineItem : contractLineItems){
            productFamilies.add(lineItem.Product_Family__c);
        }
        return String.join(new List<String>(productFamilies), ';');
    }

}